# Generated by Django 3.0.8 on 2020-07-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_self', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_to',
            field=models.CharField(max_length=30, null=True, verbose_name='回复给谁'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
