# Generated by Django 3.0.8 on 2020-08-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='article_type',
            field=models.IntegerField(default=3, verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='topic',
            name='browse_count',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
