# Generated by Django 3.0.8 on 2020-07-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(max_length=20, verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='introduce',
            field=models.CharField(max_length=90, verbose_name='文章简介'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='limit',
            field=models.CharField(max_length=10, verbose_name='文章权限'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modified_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=50, verbose_name='文章标题'),
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
