# Generated by Django 3.0.8 on 2020-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='introduce',
            field=models.CharField(max_length=150, verbose_name='文章简介'),
        ),
    ]
